import { NextResponse } from 'next/server';
import { sendEmail } from '@/lib/mailer';
import { resolveEmployerUserId } from '@/lib/employer-auth';
import { prisma } from '@/lib/prisma';

export const dynamic = 'force-dynamic';

function offerLetterHtml(params: {
  candidateName: string;
  role: string;
  salary: string;
  startDate: string;
  companyName: string;
  employerName: string;
}): string {
  return `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><style>
  body { font-family: 'Segoe UI', Arial, sans-serif; color: #111827; max-width: 700px; margin: 0 auto; padding: 40px 20px; }
  .header { border-bottom: 3px solid #5B5BD6; padding-bottom: 20px; margin-bottom: 30px; }
  .company { font-size: 22px; font-weight: 700; color: #5B5BD6; }
  .date { color: #6B7280; font-size: 14px; margin-top: 4px; }
  h1 { font-size: 20px; color: #111827; margin-bottom: 24px; }
  .highlight { background: #F5F7FF; border-left: 4px solid #5B5BD6; padding: 16px 20px; border-radius: 0 8px 8px 0; margin: 20px 0; }
  .detail-row { display: flex; gap: 8px; margin: 8px 0; font-size: 15px; }
  .label { font-weight: 600; min-width: 120px; color: #374151; }
  p { line-height: 1.7; font-size: 15px; }
  .footer { margin-top: 40px; border-top: 1px solid #E5E7EB; padding-top: 20px; font-size: 13px; color: #6B7280; }
  .signature { margin-top: 32px; }
</style></head>
<body>
  <div class="header">
    <div class="company">${params.companyName}</div>
    <div class="date">${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}</div>
  </div>

  <p>Dear <strong>${params.candidateName}</strong>,</p>

  <h1>Offer of Employment</h1>

  <p>We are delighted to extend this offer of employment to you. After careful consideration, we are pleased to offer you the position outlined below.</p>

  <div class="highlight">
    <div class="detail-row"><span class="label">Position:</span><span>${params.role}</span></div>
    <div class="detail-row"><span class="label">Salary:</span><span>${params.salary}</span></div>
    <div class="detail-row"><span class="label">Start Date:</span><span>${params.startDate}</span></div>
    <div class="detail-row"><span class="label">Company:</span><span>${params.companyName}</span></div>
  </div>

  <p>This offer is contingent upon the successful completion of our standard pre-employment background check. Please review the details above carefully and confirm your acceptance within <strong>5 business days</strong>.</p>

  <p>We look forward to welcoming you to our team and are excited about the contributions you will make.</p>

  <div class="signature">
    <p>Sincerely,</p>
    <p><strong>${params.employerName}</strong><br>${params.companyName}</p>
  </div>

  <div class="footer">
    This offer letter was generated by KaamKaaj. It is intended solely for ${params.candidateName}.
  </div>
</body>
</html>`;
}

export async function POST(request: Request) {
  try {
    const userId = await resolveEmployerUserId();
    if (!userId) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    const body = await request.json() as {
      candidateName: string;
      candidateEmail?: string;
      role: string;
      salary: string;
      startDate: string;
      sendEmail?: boolean;
    };

    const { candidateName, candidateEmail, role, salary, startDate } = body;
    if (!candidateName?.trim() || !role?.trim() || !salary?.trim() || !startDate?.trim()) {
      return NextResponse.json({ error: 'candidateName, role, salary, startDate are required' }, { status: 400 });
    }

    const [employer, company] = await Promise.all([
      prisma.user.findUnique({ where: { id: userId }, select: { name: true } }),
      prisma.company.findUnique({ where: { ownerId: userId }, select: { name: true } }),
    ]);

    const companyName  = company?.name ?? 'Company';
    const employerName = employer?.name ?? 'Hiring Manager';

    const html = offerLetterHtml({ candidateName, role, salary, startDate, companyName, employerName });

    if (body.sendEmail && candidateEmail) {
      await sendEmail({
        to: candidateEmail,
        subject: `Offer Letter — ${role} at ${companyName}`,
        html,
      });
    }

    return NextResponse.json({ ok: true, html, companyName, employerName });
  } catch (error) {
    console.error('[POST /api/employer/offer-letter]', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
