// Dashboard sample data
window.dData = {
  user: {
    name: 'Priya Sharma',
    role: 'Sales Executive',
    location: 'Mumbai, Maharashtra',
    profileCompletion: 78,
    avatarBg: 'linear-gradient(135deg,#5B5BD6,#8B8BDE)',
    initials: 'PS',
    phone: '+91 98xxx xxx10',
  },
  stats: [
    { label: 'Applications sent', value: 24,  delta: '+4 this week',  icon: 'FileText', tint: '#EBEBFF', stroke: '#5B5BD6' },
    { label: 'Interviews scheduled', value: 3, delta: '+2 this week', icon: 'Calendar', tint: '#FEF3C7', stroke: '#F59E0B' },
    { label: 'Profile views',  value: 142, delta: '+38% this week',  icon: 'Eye',      tint: '#D1FAE5', stroke: '#10B981' },
    { label: 'Saved jobs',     value: 12,  delta: '3 new today',     icon: 'Bookmark', tint: '#F3E8FF', stroke: '#8B5CF6' },
  ],
  applications: [
    {
      id: 'APP-9281', title: 'Senior Sales Executive', company: 'Tata Capital Limited',
      logo: { bg:'linear-gradient(135deg,#FF6B35,#F59E0B)', text:'TC' },
      stage: 'Interview', stageColor:'warning',
      location: 'Mumbai', salary:'₹35k–50k/mo', applied: '2 days ago',
      nextStep: 'Interview tomorrow · 10:00 AM',
    },
    {
      id: 'APP-9255', title: 'Field Sales Trainee', company: 'PolicyBazaar',
      logo: { bg:'#10B981', text:'PB' },
      stage: 'Shortlisted', stageColor:'info',
      location: 'Delhi NCR', salary:'₹16k–24k/mo', applied: '5 days ago',
      nextStep: 'Recruiter will call in 2 days',
    },
    {
      id: 'APP-9211', title: 'Customer Support', company: 'TeleCare Solutions',
      logo: { bg:'#8B5CF6', text:'TS' },
      stage: 'Applied', stageColor:'brand',
      location: 'Work from Home', salary:'₹15k–22k/mo', applied: '1 week ago',
      nextStep: 'Awaiting response',
    },
    {
      id: 'APP-9180', title: 'Junior Accountant', company: 'Krishna Traders',
      logo: { bg:'#F59E0B', text:'KT' },
      stage: 'Offered', stageColor:'success',
      location: 'Pune', salary:'₹20k–28k/mo', applied: '2 weeks ago',
      nextStep: 'Offer letter received',
    },
    {
      id: 'APP-9145', title: 'Frontend Developer', company: 'Brightline Studio',
      logo: { bg:'#5B5BD6', text:'BS' },
      stage: 'Rejected', stageColor:'danger',
      location: 'Bangalore', salary:'₹45k–70k/mo', applied: '3 weeks ago',
      nextStep: '—',
    },
  ],
  recommended: [
    { id: 'KMK-48267', title: 'Junior Accountant', company: 'Krishna Traders',
      logo: { bg:'#F59E0B', text:'KT' }, verified: false,
      location: 'Pune', salary: '₹20k–28k/mo', type: 'Full-time',
      experience: '1–3 yrs', skills: ['Tally','MS Excel','GST'], posted: '5d', applicants: 34 },
    { id: 'KMK-48254', title: 'Inside Sales Rep', company: 'Lendingkart',
      logo: { bg:'#5B5BD6', text:'LK' }, verified: true,
      location: 'Mumbai', salary: '₹28k–40k/mo', type: 'Full-time',
      experience: '1–4 yrs', skills: ['Communication','Hindi','Cold calling'], posted: '1d', applicants: 22 },
    { id: 'KMK-48240', title: 'Relationship Manager', company: 'Bajaj Finserv',
      logo: { bg:'linear-gradient(135deg,#002F87,#0E6FD9)', text:'BF' }, verified: true,
      location: 'Mumbai', salary: '₹32k–48k/mo', type: 'Full-time',
      experience: '2–5 yrs', skills: ['B2B Sales','Negotiation'], posted: '3d', applicants: 17 },
  ],
};
